name: Feature Request
about: Suggest a feature
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
    validations:
      required: true
